"use client"
import { PrinterIcon } from 'lucide-react';
import { Button } from '../ui/button';
import { AiResultType } from '@/lib/types/type';
import DeleteReportButtonComponent from './DeleteReportButtonComponent';

export default function PrintAsPDFComponent({ result }: { result: AiResultType }) {
    const handlePrint = () => {
        window.print();
    }
    const { insight, createdAt, id } = result
    const { seconds } = createdAt;
    const date = new Date(seconds * 1000);
    return (
        <div className='flex flex-col w-full md:px-36 py-5'>
            <div className='relative border p-5 print-content rounded-g max-w-3xl self-center'>
                <div className='absolute no-print flex justify-end gap-5 top-3 right-5'>
                    <Button
                        onClick={handlePrint}
                        className='no-print bg-blue-500 text-white px-4 py-2 rounded mb-5 w-fit self-center'
                    >
                        <PrinterIcon /> Save as PDF / Print
                    </Button>
                    <DeleteReportButtonComponent id={id} />
                </div>
                <h1 className='text-3xl font-bold'>Your Financial State</h1>
                <hr className='mt-2' />
                <p className='mt-4'>Date: {new Date(date).toLocaleDateString("en-US", {
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                })}</p>
                <p className='font-bold mt-6 text-2xl'>Insight</p>
                <ul className='flex flex-col gap-y-6'>
                    <li className='mt-10'><span className='font-bold'>Pattern: </span> {insight.patterns}</li>
                    <li className=''><span className='font-bold'>Risks:</span> {insight.risks}</li>
                    <li className=''><span className='font-bold'>Summary:</span> {insight.summary}</li>
                    <li><span className='font-bold'>Suggestions</span>{insight.suggestions.map((suggestion, index) => (
                        <div key={index} className='mt-4'>
                            <span>{index + 1}.  {suggestion}</span>
                        </div>
                    ))}</li>

                </ul>

                <div className='mb-0'>Generated by AI Financial Coach</div>
            </div>
        </div>
    )
}
