"use server"

import { getUserData } from "../auth/user";
import { redirect } from "next/navigation";
import admin from "../firebase/admin";
import { dateCustom } from "@/utils/nowDate";
import { FieldValue } from "firebase-admin/firestore";

export const deleteAllExpense = async () => {
    const user = await getUserData();

    if (!user || !user.uid) {
        return { success: false, error: "Unauthorized access detected." };
    }

    if (typeof user.uid !== 'string' || user.uid.length < 10) {
        throw new Error("Invalid User ID");
    }
    const db = admin.firestore();
    const batch = db.batch();
    const expensesCollectionRef = db.collection('users').doc(user.uid).collection('expenses');
    const querySnapshot = await expensesCollectionRef.get();
    querySnapshot.forEach((doc) => {
        batch.delete(doc.ref);
    });

    const userRef = db.collection('users').doc(user.uid);
    batch.update(userRef, {
        totalSpent: 0,
        totalSubscriptionSpent: 0,
        totalOneTimeSpent: 0,
        lastUpdated: new Date()
    });

    const subsRef = db.collection('users').doc(user.uid).collection('subscriptionsDetails');
    const subsQuerySnapshot = await subsRef.get();
    subsQuerySnapshot.forEach((doc) => {
        batch.delete(doc.ref);
    });

    const budgetsRef = db.collection('users').doc(user.uid).collection('budgets');
    const budgetsQuerySnapshot = await budgetsRef.get();
    budgetsQuerySnapshot.forEach((doc) => {
        batch.delete(doc.ref);
    });

    await budgetsRef.doc(dateCustom()).set({
        budget: 0,
        currency: '$',
        createdAt: FieldValue.serverTimestamp(),
        monthlyCost: 0,
        isAutoGenerated: true,

    }, { merge: true })


    await batch.commit();
    redirect('/dashboard/expenses')

}