import { UserProviderCC } from "@/components/Client/Providers/UserProvider";
import { AppSidebar } from "@/components/ui/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { getUserData } from "@/lib/auth/user";
import { User } from "@/lib/types/type";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default async function Dashboard({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const userData = await getUserData();
    return (

        <div
            className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased dark relative `}
        >
            <SidebarProvider>
                <UserProviderCC initialData={userData as User}>
                    <AppSidebar />
                    <SidebarTrigger />
                    <main className="w-full relative">
                        {children}
                    </main>
                </UserProviderCC>
            </SidebarProvider>
        </div>
    );
}
