import LogoutClientComponent from "@/components/Client/Auth/LogoutClientComponent";
import { UserProviderCC } from "@/components/Client/Providers/UserProvider";
import { AppSidebar } from "@/components/ui/AppSidebar";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuPortal, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { getUserData } from "@/lib/auth/user";
import { User } from "@/lib/types/type";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { use } from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default async function Dashboard({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    let userData: User | undefined = undefined;
    try {
        userData = await getUserData();
    } catch (err) {
        console.log(err)
    }
    return (

        <div
            className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased dark relative `}
        >
            <SidebarProvider>
                <UserProviderCC initialData={userData as User}>
                    <AppSidebar />
                    <SidebarTrigger />
                    <main className="w-full relative">
                        {children}
                    </main>
                </UserProviderCC>
            </SidebarProvider>
        </div>
    );
}
