import LogoutClientComponent from "@/components/Client/Auth/LogoutClientComponent";
import { AppSidebar } from "@/components/ui/AppSidebar";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuPortal, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import admin from "@/lib/firebase/admin";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import Link from "next/link";
import { redirect } from "next/navigation";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default async function Dashboard({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = cookies();

    const sessionCookie = (await cookieStore).get('sessionToken')?.value || ''

    if (!sessionCookie) {
        // redirect('//login')
        // return null
    }
    let userData: { UserEmail: string, userUid: string, photo: string, displayName: string } | null = null;
    try {
        const decodedClaims = await admin.auth().verifySessionCookie(sessionCookie, true)
        userData = {
            UserEmail: decodedClaims.email || '',
            userUid: decodedClaims.uid || '',
            photo: decodedClaims.picture || '',
            displayName: decodedClaims.name || '',
        }

    } catch (error) {
        console.log(error)
    }

    return (

        <div
            className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased dark relative `}
        >
            <header className="p-5 bg-gray-600/30 text-white  mx-auto rounded-md flex justify-between items-center sticky top-0 z-50 no-print">
                <div>
                    <a href="/">Ana Sayfa</a>
                </div>
                <div className="flex items-center gap-5">

                    <Avatar>
                        {userData?.photo ? (
                            <AvatarImage src={userData.photo} />
                        ) : (
                            <AvatarImage src={'https://github.com/shadcn.png'} />
                        )}


                        <AvatarFallback>CN</AvatarFallback>
                    </Avatar>
                    <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                            <Button variant="outline">Open</Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent className="w-56" align="start">
                            <DropdownMenuLabel>My Account</DropdownMenuLabel>
                            <DropdownMenuGroup>
                                <DropdownMenuItem>
                                    Profile
                                    <DropdownMenuShortcut>⇧⌘P</DropdownMenuShortcut>
                                </DropdownMenuItem>
                                <DropdownMenuItem>
                                    Billing
                                    <DropdownMenuShortcut>⌘B</DropdownMenuShortcut>
                                </DropdownMenuItem>
                                <DropdownMenuItem>
                                    Settings
                                    <DropdownMenuShortcut>⌘S</DropdownMenuShortcut>
                                </DropdownMenuItem>
                                <DropdownMenuItem>
                                    Keyboard shortcuts
                                    <DropdownMenuShortcut>⌘K</DropdownMenuShortcut>
                                </DropdownMenuItem>
                            </DropdownMenuGroup>
                            <DropdownMenuSeparator />
                            <DropdownMenuGroup>
                                <DropdownMenuItem>Team</DropdownMenuItem>
                                <DropdownMenuSub>
                                    <DropdownMenuSubTrigger>Invite users</DropdownMenuSubTrigger>
                                    <DropdownMenuPortal>
                                        <DropdownMenuSubContent>
                                            <DropdownMenuItem>Email</DropdownMenuItem>
                                            <DropdownMenuItem>Message</DropdownMenuItem>
                                            <DropdownMenuSeparator />
                                            <DropdownMenuItem>More...</DropdownMenuItem>
                                        </DropdownMenuSubContent>
                                    </DropdownMenuPortal>
                                </DropdownMenuSub>
                                <DropdownMenuItem>
                                    New Team
                                    <DropdownMenuShortcut>⌘+T</DropdownMenuShortcut>
                                </DropdownMenuItem>
                            </DropdownMenuGroup>
                            <DropdownMenuSeparator />
                            <DropdownMenuItem>GitHub</DropdownMenuItem>
                            <DropdownMenuItem>Support</DropdownMenuItem>
                            <DropdownMenuItem disabled>API</DropdownMenuItem>
                            <DropdownMenuSeparator />
                            <LogoutClientComponent />

                        </DropdownMenuContent>
                    </DropdownMenu>
                </div>
                {userData ? null : <Link href={'/auth/login'}>Login Page</Link>}
            </header>
            <SidebarProvider>

                <AppSidebar />
                <SidebarTrigger />
                <main className="w-full relative">
                    {children}
                </main>
            </SidebarProvider>
        </div>
    );
}
